"""
Django settings for thrift_app project.

Generated by 'django-admin startproject' using Django 4.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'secret')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['43aa-197-237-38-104.ngrok-free.app', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # local app
    'authentication',
    'mozilla_django_oidc', #load after auth
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.OIDCSessionRefreshMiddleware'
]

ROOT_URLCONF = 'thrift_app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR.joinpath("thrift_app/template")
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'thrift_app.wsgi.application'

# Adding 'mozilla_django_oidc' authentication backend
AUTHENTICATION_BACKENDS = (
    "core.backends.CustomOIDCAuthenticationBackend",
    "django.contrib.auth.backends.ModelBackend",
)


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# homepage view
LOGIN_REDIRECT_URL = "index"
LOGOUT_REDIRECT_URL = "index"


# Configuring okta

OKTA_DOMAIN = os.getenv("OKTA_DOMAIN", "")
OIDC_RP_CLIENT_ID = os.getenv("OIDC_RP_CLIENT_ID", "")
OIDC_RP_CLIENT_SECRET = os.getenv("OIDC_RP_CLIENT_SECRET", "")

# Define the OIDC redirect URI here
OIDC_REDIRECT_URI = os.getenv(
    "OIDC_REDIRECT_URI", "https: // ef0c-197-237-38-104.ngrok-free.app/authorization-code/callback"
    
)

OIDC_RP_SIGN_ALGO = "RS256"
# The OIDC authorization endpoint
OIDC_OP_AUTHORIZATION_ENDPOINT = f"https://{OKTA_DOMAIN}/oauth2/default/v1/authorize"
# User's endpoint
OIDC_OP_USER_ENDPOINT = (f"https://{OKTA_DOMAIN}/oauth2/default/v1/userinfo")
# The OIDC JWKS endpoint
OIDC_OP_JWKS_ENDPOINT = (f"https://{OKTA_DOMAIN}/oauth2/default/v1/keys")
# The OIDC token revocation endpoint
OIDC_OP_TOKEN_REVOKE_ENDPOINT = f"https://{OKTA_DOMAIN}/oauth2/default/v1/revoke"


OIDC_RENEW_ID_TOKEN_EXPIRY_SECONDS = 60 * 60  # 1 hour


OIDC_STORE_ACCESS_TOKEN = os.getenv(
    "OIDC_STORE_ACCESS_TOKEN", True
)  # Store the access token in the OIDC backend
OIDC_STORE_ID_TOKEN = os.getenv(
    "OIDC_STORE_ID_TOKEN", True
)  # Store the ID token in the OIDC backend
OIDC_STORE_REFRESH_TOKEN = os.getenv(
    "OIDC_STORE_REFRESH_TOKEN", True
)  # Store the refresh token in the OIDC backend

OIDC_RP_SCOPES = os.getenv(
    "OIDC_RP_SCOPES", "openid profile email offline_access"
)  # The OIDC scopes to request

OIDC_EXEMPT_URLS = [
    "oidc_authentication_init",
    "oidc_authentication_callback",
    "logout",
]
